# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import datetime
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('primeExchange', '0004_commodities_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadBillingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('RecordID', models.IntegerField()),
                ('ClientID', models.CharField(max_length=30)),
                ('ColumnName', models.CharField(max_length=30)),
                ('ColumnValue', models.CharField(null=True, max_length=30)),
                ('ErrorMessage', models.CharField(max_length=250)),
                ('JSONString', models.CharField(max_length=2000)),
                ('UpdatedOn', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBillingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('RecordID', models.IntegerField()),
                ('ClientID', models.CharField(max_length=30)),
                ('UHID', models.IntegerField()),
                ('AdmissionNumber', models.BigIntegerField()),
                ('RegistrationDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 777102, tzinfo=utc))),
                ('RegistrationNumber', models.IntegerField()),
                ('BillingDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 18, 56, 29, 777129))),
                ('BillingNumber', models.BigIntegerField()),
                ('TimeOfBilling', models.TimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 18, 56, 29, 777154))),
                ('PatientZIP', models.IntegerField(null=True)),
                ('PatientDateOfBirth', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 777181, tzinfo=utc))),
                ('PatientGender', models.CharField(null=True, max_length=30)),
                ('ServiceCode', models.CharField(max_length=30)),
                ('ServiceName', models.CharField(max_length=100)),
                ('NumberOfUnitsOfService', models.IntegerField()),
                ('ServiceAmount', models.IntegerField()),
                ('DoctorName', models.CharField(max_length=100)),
                ('FinalBillAmount', models.IntegerField(null=True)),
                ('FinalDiscountAmount', models.IntegerField(null=True)),
                ('PaymentMode', models.CharField(null=True, max_length=30)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, null=True, max_digits=18)),
                ('PaymentDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 777296, tzinfo=utc))),
                ('FinalBillingID', models.BigIntegerField(null=True)),
                ('FinalEncounterID', models.BigIntegerField(null=True)),
                ('InsuranceCoverage', models.CharField(null=True, max_length=30)),
                ('EmployerBasedInsurance', models.CharField(null=True, max_length=30)),
                ('InsuranceCompanyName', models.CharField(null=True, max_length=100)),
                ('PatientEducation', models.CharField(null=True, max_length=30)),
                ('EmploymentType', models.CharField(null=True, max_length=30)),
                ('PatientEmployer', models.CharField(null=True, max_length=30)),
                ('PatientAnnualIncomeRange', models.IntegerField(null=True)),
                ('FrequencyOfGleneaglesVisit', models.CharField(null=True, max_length=30)),
                ('LifestylePattern', models.CharField(null=True, max_length=30)),
                ('TreatmentPlan', models.CharField(null=True, max_length=30)),
                ('Rx', models.CharField(null=True, max_length=30)),
                ('TestsPrescribed', models.CharField(null=True, max_length=30)),
                ('NextVisitDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 777451, tzinfo=utc))),
                ('Referrals', models.CharField(null=True, max_length=30)),
                ('JSONString', models.CharField(max_length=2000)),
                ('DataExchangeStatus', models.CharField(null=True, max_length=1000)),
                ('UpdatedBy', models.CharField(null=True, max_length=30)),
                ('UpdatedOn', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotTobePredictedBillingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('RecordID', models.IntegerField()),
                ('ClientID', models.CharField(max_length=30)),
                ('UHID', models.IntegerField()),
                ('AdmissionNumber', models.BigIntegerField()),
                ('RegistrationDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 779492, tzinfo=utc))),
                ('RegistrationNumber', models.IntegerField()),
                ('BillingDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 779523, tzinfo=utc))),
                ('BillingNumber', models.BigIntegerField()),
                ('TimeOfBilling', models.TimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 18, 56, 29, 779547))),
                ('PatientZIP', models.IntegerField(null=True)),
                ('PatientDateOfBirth', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 779573, tzinfo=utc))),
                ('PatientGender', models.CharField(null=True, max_length=30)),
                ('ServiceCode', models.CharField(max_length=30)),
                ('ServiceName', models.CharField(max_length=100)),
                ('NumberOfUnitsOfService', models.IntegerField()),
                ('ServiceAmount', models.IntegerField()),
                ('DoctorName', models.CharField(max_length=100)),
                ('FinalBillAmount', models.IntegerField(null=True)),
                ('FinalDiscountAmount', models.IntegerField(null=True)),
                ('PaymentMode', models.CharField(null=True, max_length=30)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, null=True, max_digits=18)),
                ('PaymentDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 779697, tzinfo=utc))),
                ('FinalBillingID', models.BigIntegerField(null=True)),
                ('FinalEncounterID', models.BigIntegerField(null=True)),
                ('InsuranceCoverage', models.CharField(null=True, max_length=30)),
                ('EmployerBasedInsurance', models.CharField(null=True, max_length=30)),
                ('InsuranceCompanyName', models.CharField(null=True, max_length=100)),
                ('PatientEducation', models.CharField(null=True, max_length=30)),
                ('EmploymentType', models.CharField(null=True, max_length=30)),
                ('PatientEmployer', models.CharField(null=True, max_length=30)),
                ('PatientAnnualIncomeRange', models.IntegerField(null=True)),
                ('FrequencyOfGleneaglesVisit', models.CharField(null=True, max_length=30)),
                ('LifestylePattern', models.CharField(null=True, max_length=30)),
                ('TreatmentPlan', models.CharField(null=True, max_length=30)),
                ('Rx', models.CharField(null=True, max_length=30)),
                ('TestsPrescribed', models.CharField(null=True, max_length=30)),
                ('NextVisitDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 779854, tzinfo=utc))),
                ('Referrals', models.CharField(null=True, max_length=30)),
                ('JSONString', models.CharField(max_length=2000)),
                ('DataExchangeStatus', models.CharField(null=True, max_length=1000)),
                ('UpdatedBy', models.CharField(null=True, max_length=30)),
                ('UpdatedOn', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawBillingRecord',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientID', models.CharField(null=True, max_length=30)),
                ('UHID', models.CharField(null=True, max_length=30)),
                ('AdmissionNumber', models.CharField(null=True, max_length=30)),
                ('RegistrationDate', models.CharField(null=True, max_length=30)),
                ('RegistrationNumber', models.CharField(null=True, max_length=30)),
                ('BillingDate', models.CharField(null=True, max_length=30)),
                ('BillingNumber', models.CharField(null=True, max_length=30)),
                ('TimeOfBilling', models.CharField(null=True, max_length=30)),
                ('PatientZIP', models.CharField(null=True, max_length=30)),
                ('PatientDateOfBirth', models.CharField(null=True, max_length=30)),
                ('PatientGender', models.CharField(null=True, max_length=30)),
                ('ServiceCode', models.CharField(null=True, max_length=30)),
                ('ServiceName', models.CharField(null=True, max_length=100)),
                ('NumberOfUnitsOfService', models.CharField(null=True, max_length=30)),
                ('ServiceAmount', models.CharField(null=True, max_length=30)),
                ('DoctorName', models.CharField(null=True, max_length=100)),
                ('FinalBillAmount', models.CharField(null=True, max_length=30)),
                ('FinalDiscountAmount', models.CharField(null=True, max_length=30)),
                ('PaymentMode', models.CharField(null=True, max_length=30)),
                ('PaymentAmount', models.CharField(null=True, max_length=30)),
                ('PaymentDate', models.CharField(null=True, max_length=30)),
                ('FinalBillingID', models.CharField(null=True, max_length=30)),
                ('FinalEncounterID', models.CharField(null=True, max_length=30)),
                ('InsuranceCoverage', models.CharField(null=True, max_length=30)),
                ('EmployerBasedInsurance', models.CharField(null=True, max_length=30)),
                ('InsuranceCompanyName', models.CharField(null=True, max_length=100)),
                ('PatientEducation', models.CharField(null=True, max_length=30)),
                ('EmploymentType', models.CharField(null=True, max_length=30)),
                ('PatientEmployer', models.CharField(null=True, max_length=100)),
                ('PatientAnnualIncomeRange', models.CharField(null=True, max_length=30)),
                ('FrequencyOfGleneaglesVisit', models.CharField(null=True, max_length=30)),
                ('LifestylePattern', models.CharField(null=True, max_length=30)),
                ('TreatmentPlan', models.CharField(null=True, max_length=30)),
                ('Rx', models.CharField(null=True, max_length=30)),
                ('TestsPrescribed', models.CharField(null=True, max_length=30)),
                ('NextVisitDate', models.CharField(null=True, max_length=30)),
                ('Referrals', models.CharField(null=True, max_length=30)),
                ('JSONString', models.CharField(max_length=2000)),
                ('DataExchangeStatus', models.CharField(null=True, max_length=1000)),
                ('UpdatedBy', models.CharField(null=True, max_length=30)),
                ('UpdatedOn', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rawErrorRecord',
            fields=[
                ('ErrorRecordID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientID', models.CharField(max_length=30)),
                ('JSONString', models.CharField(max_length=2000)),
                ('ErrorMessage', models.CharField(max_length=250)),
                ('UpdatedOn', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TobePredictedBillingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('RecordID', models.IntegerField()),
                ('ClientID', models.CharField(max_length=30)),
                ('UHID', models.IntegerField()),
                ('AdmissionNumber', models.BigIntegerField()),
                ('RegistrationDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 778266, tzinfo=utc))),
                ('RegistrationNumber', models.IntegerField()),
                ('BillingDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 18, 56, 29, 778293))),
                ('BillingNumber', models.BigIntegerField()),
                ('TimeOfBilling', models.TimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 778320, tzinfo=utc))),
                ('PatientZIP', models.IntegerField(null=True)),
                ('PatientDateOfBirth', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 778343, tzinfo=utc))),
                ('PatientGender', models.CharField(null=True, max_length=30)),
                ('ServiceCode', models.CharField(max_length=30)),
                ('ServiceName', models.CharField(max_length=100)),
                ('NumberOfUnitsOfService', models.IntegerField()),
                ('ServiceAmount', models.IntegerField()),
                ('DoctorName', models.CharField(max_length=100)),
                ('FinalBillAmount', models.IntegerField(null=True)),
                ('FinalDiscountAmount', models.IntegerField(null=True)),
                ('PaymentMode', models.CharField(null=True, max_length=30)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, null=True, max_digits=18)),
                ('PaymentDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 778458, tzinfo=utc))),
                ('FinalBillingID', models.BigIntegerField(null=True)),
                ('FinalEncounterID', models.BigIntegerField(null=True)),
                ('InsuranceCoverage', models.CharField(null=True, max_length=30)),
                ('EmployerBasedInsurance', models.CharField(null=True, max_length=30)),
                ('InsuranceCompanyName', models.CharField(null=True, max_length=100)),
                ('PatientEducation', models.CharField(null=True, max_length=30)),
                ('EmploymentType', models.CharField(null=True, max_length=30)),
                ('PatientEmployer', models.CharField(null=True, max_length=30)),
                ('PatientAnnualIncomeRange', models.IntegerField(null=True)),
                ('FrequencyOfGleneaglesVisit', models.CharField(null=True, max_length=30)),
                ('LifestylePattern', models.CharField(null=True, max_length=30)),
                ('TreatmentPlan', models.CharField(null=True, max_length=30)),
                ('Rx', models.CharField(null=True, max_length=30)),
                ('TestsPrescribed', models.CharField(null=True, max_length=30)),
                ('NextVisitDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 778681, tzinfo=utc))),
                ('Referrals', models.CharField(null=True, max_length=30)),
                ('JSONString', models.CharField(max_length=2000)),
                ('DataExchangeStatus', models.CharField(null=True, max_length=1000)),
                ('UpdatedBy', models.CharField(null=True, max_length=30)),
                ('UpdatedOn', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedBillingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('RecordID', models.IntegerField()),
                ('ClientID', models.CharField(max_length=30)),
                ('UHID', models.IntegerField()),
                ('AdmissionNumber', models.BigIntegerField()),
                ('RegistrationDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 775363, tzinfo=utc))),
                ('RegistrationNumber', models.IntegerField()),
                ('BillingDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 775397, tzinfo=utc))),
                ('BillingNumber', models.BigIntegerField()),
                ('TimeOfBilling', models.TimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 18, 56, 29, 775423))),
                ('PatientZIP', models.IntegerField(null=True)),
                ('PatientDateOfBirth', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 775458, tzinfo=utc))),
                ('PatientGender', models.CharField(null=True, max_length=30)),
                ('ServiceCode', models.CharField(max_length=30)),
                ('ServiceName', models.CharField(max_length=100)),
                ('NumberOfUnitsOfService', models.IntegerField()),
                ('ServiceAmount', models.IntegerField()),
                ('DoctorName', models.CharField(max_length=100)),
                ('FinalBillAmount', models.IntegerField(null=True)),
                ('FinalDiscountAmount', models.IntegerField(null=True)),
                ('PaymentMode', models.CharField(null=True, max_length=30)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, null=True, max_digits=18)),
                ('PaymentDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 775582, tzinfo=utc))),
                ('FinalBillingID', models.BigIntegerField(null=True)),
                ('FinalEncounterID', models.BigIntegerField(null=True)),
                ('InsuranceCoverage', models.CharField(null=True, max_length=30)),
                ('EmployerBasedInsurance', models.CharField(null=True, max_length=30)),
                ('InsuranceCompanyName', models.CharField(null=True, max_length=100)),
                ('PatientEducation', models.CharField(null=True, max_length=30)),
                ('EmploymentType', models.CharField(null=True, max_length=30)),
                ('PatientEmployer', models.CharField(null=True, max_length=30)),
                ('PatientAnnualIncomeRange', models.IntegerField(null=True)),
                ('FrequencyOfGleneaglesVisit', models.CharField(null=True, max_length=30)),
                ('LifestylePattern', models.CharField(null=True, max_length=30)),
                ('TreatmentPlan', models.CharField(null=True, max_length=30)),
                ('Rx', models.CharField(null=True, max_length=30)),
                ('TestsPrescribed', models.CharField(null=True, max_length=30)),
                ('NextVisitDate', models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 11, 15, 13, 26, 29, 775785, tzinfo=utc))),
                ('Referrals', models.CharField(null=True, max_length=30)),
                ('JSONString', models.CharField(max_length=2000)),
                ('DataExchangeStatus', models.CharField(null=True, max_length=1000)),
                ('UpdatedBy', models.CharField(null=True, max_length=30)),
                ('UpdatedOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
