from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
import datetime as dt
from datetime import datetime

# Create your models here.



class Profile(models.Model):
	
	ROLES=(('Prime_admin','Prime_Administrator'),
	('Hospital_management','Hospital_Management'),
	('Hospital_admin','Hospital_Administrator'),
	)
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	first_name=models.CharField(max_length=20)
	last_name=models.CharField(max_length=20)
	username=models.CharField(max_length=10)
	password = models.CharField(max_length=50)
	email=models.EmailField(max_length=30)
	date = models.DateField(("Date"), default=dt.date.today)
	role=models.CharField(default="Prime_Administrator",choices=ROLES,max_length=30)
	mobile= models.CharField(max_length=10)
	office_contact=models.CharField(max_length=10)
	
	
	def __str__(self):
		return self.user.username

	


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()	





class Commodities(models.Model):
	commodity=models.CharField(max_length=20)
	price=models.IntegerField()
	date=models.DateField(default=dt.date.today)


	def __str__(self):
		return self.commodity



class rawErrorRecord(models.Model):
    ErrorRecordID = models.AutoField(primary_key=True)
    ClientID = models.CharField(max_length=30,null=False)    
    JSONString = models.CharField(max_length=2000,null=False)
    ErrorMessage = models.CharField(max_length=250,null=False)
    UpdatedOn = models.DateTimeField(default=timezone.now, null=True) 

class RawBillingRecord(models.Model):
    RecordID = models.AutoField(primary_key=True)
    ClientID = models.CharField(max_length=30,null=True)
    UHID =  models.CharField(max_length=30,null=True)
    AdmissionNumber = models.CharField(max_length=30,null=True)
    RegistrationDate = models.CharField(max_length=30,null=True)
    RegistrationNumber = models.CharField(max_length=30,null=True)
    BillingDate = models.CharField(max_length=30,null=True)
    BillingNumber = models.CharField(max_length=30,null=True) 
    TimeOfBilling = models.CharField(max_length=30,null=True)
    PatientZIP = models.CharField(max_length=30,null=True)
    PatientDateOfBirth = models.CharField(max_length=30,null=True)
    PatientGender = models.CharField(max_length=30,null=True)
    ServiceCode = models.CharField(max_length=30,null=True)
    ServiceName = models.CharField(max_length=100,null=True)
    NumberOfUnitsOfService = models.CharField(max_length=30,null=True)
    ServiceAmount = models.CharField(max_length=30,null=True)
    DoctorName = models.CharField(max_length=100,null=True)
    FinalBillAmount = models.CharField(max_length=30,null=True)
    FinalDiscountAmount = models.CharField(max_length=30,null=True)
    PaymentMode = models.CharField(max_length=30,null=True)
    PaymentAmount = models.CharField(max_length=30,null=True)
    PaymentDate = models.CharField(max_length=30,null=True)
    FinalBillingID = models.CharField(max_length=30,null=True)
    FinalEncounterID = models.CharField(max_length=30,null=True)
    InsuranceCoverage = models.CharField(max_length=30,null=True)
    EmployerBasedInsurance = models.CharField(max_length=30,null=True)
    InsuranceCompanyName = models.CharField(max_length=100,null=True)
    PatientEducation = models.CharField(max_length=30,null=True)
    EmploymentType = models.CharField(max_length=30,null=True)
    PatientEmployer = models.CharField(max_length=100,null=True)
    PatientAnnualIncomeRange = models.CharField(max_length=30,null=True)
    FrequencyOfGleneaglesVisit = models.CharField(max_length=30,null=True)
    LifestylePattern = models.CharField(max_length=30,null=True)
    TreatmentPlan = models.CharField(max_length=30,null=True)
    Rx = models.CharField(max_length=30,null=True)
    TestsPrescribed = models.CharField(max_length=30,null=True)
    NextVisitDate = models.CharField(max_length=30,null=True)
    Referrals = models.CharField(max_length=30,null=True)  
    JSONString = models.CharField(max_length=2000,null=False)    
    DataExchangeStatus = models.CharField(max_length=1000,null=True)
    UpdatedBy = models.CharField(max_length=30,null=True)
    UpdatedOn = models.DateTimeField(default=timezone.now, null=True) 

class ValidatedBillingRecord(models.Model):
    RecordID = models.IntegerField(null = False)
    ClientID = models.CharField(max_length=30,null = False)
    UHID =  models.IntegerField(null = False)
    AdmissionNumber = models.BigIntegerField(null = False)
    RegistrationDate =  models.DateTimeField(timezone.now(),null = False)
    RegistrationNumber = models.IntegerField (null = False)
    BillingDate = models.DateTimeField(timezone.now(),null = False)   
    BillingNumber = models.BigIntegerField(null = False) 
    TimeOfBilling = models.TimeField(datetime.now(),null = True)
    PatientZIP = models.IntegerField (null = True)
    PatientDateOfBirth = models.DateTimeField( timezone.now(),null = True) 
    PatientGender = models.CharField(max_length=30,null = True)
    ServiceCode = models.CharField(max_length=30,null = False)  
    ServiceName = models.CharField(max_length=100,null = False) 
    NumberOfUnitsOfService = models.IntegerField(null = False)
    ServiceAmount = models.IntegerField (null = False)
    DoctorName = models.CharField(max_length=100,null = False)  
    FinalBillAmount = models.IntegerField (null = True)
    FinalDiscountAmount = models.IntegerField (null = True)
    PaymentMode = models.CharField(max_length=30,null = True) 
    PaymentAmount = models.DecimalField (max_digits=18,decimal_places=2,null = True)
    PaymentDate = models.DateTimeField(timezone.now(),null=True)   
    FinalBillingID = models.BigIntegerField(null=True)
    FinalEncounterID = models.BigIntegerField(null=True)
    InsuranceCoverage = models.CharField(max_length=30,null=True) 
    EmployerBasedInsurance = models.CharField(max_length=30,null=True)
    InsuranceCompanyName = models.CharField(max_length=100,null=True)
    PatientEducation = models.CharField(max_length=30,null=True) 
    EmploymentType = models.CharField(max_length=30,null=True) 
    PatientEmployer = models.CharField(max_length=30,null=True) 
    PatientAnnualIncomeRange = models.IntegerField(null=True)
    FrequencyOfGleneaglesVisit = models.CharField(max_length=30,null=True) 
    LifestylePattern = models.CharField(max_length=30,null=True) 
    TreatmentPlan = models.CharField(max_length=30,null=True)
    Rx = models.CharField(max_length=30,null=True) 
    TestsPrescribed = models.CharField(max_length=30,null=True) 
    NextVisitDate = models.DateTimeField(timezone.now(),null=True)  
    Referrals = models.CharField(max_length=30,null=True) 
    JSONString = models.CharField(max_length=2000,null=False)
    DataExchangeStatus = models.CharField(max_length=1000,null=True)    
    UpdatedBy = models.CharField(max_length=30,null=True)
    UpdatedOn = models.DateTimeField(default=timezone.now,null=False)

class BadBillingRecord(models.Model):
    RecordID = models.IntegerField (null=False)
    ClientID = models.CharField(max_length=30,null=False)    
    ColumnName = models.CharField(max_length=30,null=False)
    ColumnValue = models.CharField(max_length=30,null=True)
    ErrorMessage = models.CharField(max_length=250,null=False)
    JSONString = models.CharField(max_length=2000,null=False)
    UpdatedOn = models.DateTimeField(default=timezone.now, null=True) 


class HistoricalBillingData(models.Model):
    RecordID = models.IntegerField(null = False)
    ClientID = models.CharField(max_length=30,null=False)    
    UHID =  models.IntegerField(null = False)
    AdmissionNumber = models.BigIntegerField(null = False)
    RegistrationDate =  models.DateTimeField(timezone.now(),null = False)
    RegistrationNumber = models.IntegerField (null = False)
    BillingDate = models.DateTimeField(datetime.now(),null = False)   
    BillingNumber = models.BigIntegerField(null = False) 
    TimeOfBilling = models.TimeField(datetime.now(),null = True)
    PatientZIP = models.IntegerField (null = True)
    PatientDateOfBirth = models.DateTimeField( timezone.now(),null = True) 
    PatientGender = models.CharField(max_length=30,null = True)
    ServiceCode = models.CharField(max_length=30,null = False)  
    ServiceName = models.CharField(max_length=100,null = False) 
    NumberOfUnitsOfService = models.IntegerField(null = False)
    ServiceAmount = models.IntegerField (null = False)
    DoctorName = models.CharField(max_length=100,null = False)  
    FinalBillAmount = models.IntegerField (null = True)
    FinalDiscountAmount = models.IntegerField (null = True)
    PaymentMode = models.CharField(max_length=30,null = True) 
    PaymentAmount = models.DecimalField (max_digits=18,decimal_places=2,null = True)
    PaymentDate = models.DateTimeField(timezone.now(),null=True)   
    FinalBillingID = models.BigIntegerField(null=True)
    FinalEncounterID = models.BigIntegerField(null=True)
    InsuranceCoverage = models.CharField(max_length=30,null=True) 
    EmployerBasedInsurance = models.CharField(max_length=30,null=True)
    InsuranceCompanyName = models.CharField(max_length=100,null=True)
    PatientEducation = models.CharField(max_length=30,null=True) 
    EmploymentType = models.CharField(max_length=30,null=True) 
    PatientEmployer = models.CharField(max_length=30,null=True) 
    PatientAnnualIncomeRange = models.IntegerField(null=True)
    FrequencyOfGleneaglesVisit = models.CharField(max_length=30,null=True) 
    LifestylePattern = models.CharField(max_length=30,null=True) 
    TreatmentPlan = models.CharField(max_length=30,null=True)
    Rx = models.CharField(max_length=30,null=True) 
    TestsPrescribed = models.CharField(max_length=30,null=True) 
    NextVisitDate = models.DateTimeField(timezone.now(),null=True)  
    Referrals = models.CharField(max_length=30,null=True) 
    JSONString = models.CharField(max_length=2000,null=False)
    DataExchangeStatus = models.CharField(max_length=1000,null=True)    
    UpdatedBy = models.CharField(max_length=30,null=True)
    UpdatedOn = models.DateTimeField(default=timezone.now, null=True) 

class TobePredictedBillingRecord(models.Model):
    RecordID = models.IntegerField(null = False)
    ClientID = models.CharField(max_length=30,null=False)    
    UHID =  models.IntegerField(null = False)
    AdmissionNumber = models.BigIntegerField(null = False)
    RegistrationDate =  models.DateTimeField(timezone.now(),null = False)
    RegistrationNumber = models.IntegerField(null = False)
    BillingDate = models.DateTimeField(datetime.now(),null = False)   
    BillingNumber = models.BigIntegerField(null = False) 
    TimeOfBilling = models.TimeField(timezone.now(),null = True)
    PatientZIP = models.IntegerField (null = True)
    PatientDateOfBirth = models.DateTimeField( timezone.now(),null = True) 
    PatientGender = models.CharField(max_length=30,null = True)
    ServiceCode = models.CharField(max_length=30,null = False)  
    ServiceName = models.CharField(max_length=100,null = False) 
    NumberOfUnitsOfService = models.IntegerField(null = False)
    ServiceAmount = models.IntegerField (null = False)
    DoctorName = models.CharField(max_length=100,null = False)  
    FinalBillAmount = models.IntegerField (null = True)
    FinalDiscountAmount = models.IntegerField (null = True)
    PaymentMode = models.CharField(max_length=30,null = True) 
    PaymentAmount = models.DecimalField (max_digits=18,decimal_places=2,null = True)
    PaymentDate = models.DateTimeField(timezone.now(),null=True)   
    FinalBillingID = models.BigIntegerField(null=True)
    FinalEncounterID = models.BigIntegerField(null=True)
    InsuranceCoverage = models.CharField(max_length=30,null=True) 
    EmployerBasedInsurance = models.CharField(max_length=30,null=True)
    InsuranceCompanyName = models.CharField(max_length=100,null=True)
    PatientEducation = models.CharField(max_length=30,null=True) 
    EmploymentType = models.CharField(max_length=30,null=True) 
    PatientEmployer = models.CharField(max_length=30,null=True) 
    PatientAnnualIncomeRange = models.IntegerField(null=True)
    FrequencyOfGleneaglesVisit = models.CharField(max_length=30,null=True) 
    LifestylePattern = models.CharField(max_length=30,null=True) 
    TreatmentPlan = models.CharField(max_length=30,null=True)
    Rx = models.CharField(max_length=30,null=True) 
    TestsPrescribed = models.CharField(max_length=30,null=True) 
    NextVisitDate = models.DateTimeField(timezone.now(),null=True)  
    Referrals = models.CharField(max_length=30,null=True) 
    JSONString = models.CharField(max_length=2000,null=False)
    DataExchangeStatus = models.CharField(max_length=1000,null=True)
    UpdatedBy = models.CharField(max_length=30,null=True)
    UpdatedOn = models.DateTimeField(default=timezone.now, null=True) 


class NotTobePredictedBillingRecord(models.Model):
    RecordID = models.IntegerField(null = False)
    ClientID = models.CharField(max_length=30,null=False)    
    UHID =  models.IntegerField(null = False)
    AdmissionNumber = models.BigIntegerField(null = False)
    RegistrationDate =  models.DateTimeField(timezone.now(),null = False)
    RegistrationNumber = models.IntegerField (null = False)
    BillingDate = models.DateTimeField(timezone.now(),null = False)   
    BillingNumber = models.BigIntegerField(null = False) 
    TimeOfBilling = models.TimeField(datetime.now(),null = True)
    PatientZIP = models.IntegerField (null = True)
    PatientDateOfBirth = models.DateTimeField( timezone.now(),null = True) 
    PatientGender = models.CharField(max_length=30,null = True)
    ServiceCode = models.CharField(max_length=30,null = False)  
    ServiceName = models.CharField(max_length=100,null = False) 
    NumberOfUnitsOfService = models.IntegerField(null = False)
    ServiceAmount = models.IntegerField (null = False)
    DoctorName = models.CharField(max_length=100,null = False)  
    FinalBillAmount = models.IntegerField (null = True)
    FinalDiscountAmount = models.IntegerField (null = True)
    PaymentMode = models.CharField(max_length=30,null = True) 
    PaymentAmount = models.DecimalField (max_digits=18,decimal_places=2,null = True)
    PaymentDate = models.DateTimeField(timezone.now(),null=True)   
    FinalBillingID = models.BigIntegerField(null=True)
    FinalEncounterID = models.BigIntegerField(null=True)
    InsuranceCoverage = models.CharField(max_length=30,null=True) 
    EmployerBasedInsurance = models.CharField(max_length=30,null=True)
    InsuranceCompanyName = models.CharField(max_length=100,null=True)
    PatientEducation = models.CharField(max_length=30,null=True) 
    EmploymentType = models.CharField(max_length=30,null=True) 
    PatientEmployer = models.CharField(max_length=30,null=True) 
    PatientAnnualIncomeRange = models.IntegerField(null=True)
    FrequencyOfGleneaglesVisit = models.CharField(max_length=30,null=True) 
    LifestylePattern = models.CharField(max_length=30,null=True) 
    TreatmentPlan = models.CharField(max_length=30,null=True)
    Rx = models.CharField(max_length=30,null=True) 
    TestsPrescribed = models.CharField(max_length=30,null=True) 
    NextVisitDate = models.DateTimeField(timezone.now(),null=True)  
    Referrals = models.CharField(max_length=30,null=True) 
    JSONString = models.CharField(max_length=2000,null=False)
    DataExchangeStatus = models.CharField(max_length=1000,null=True)
    UpdatedBy = models.CharField(max_length=30,null=True)
    UpdatedOn = models.DateTimeField(default=timezone.now, null=True) 
